// <auto-generated />
namespace Animais360.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addAreaQuestaoAjuda1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addAreaQuestaoAjuda1));
        
        string IMigrationMetadata.Id
        {
            get { return "201405200149133_addAreaQuestaoAjuda1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
