// <auto-generated />
namespace Animais360.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class JogoToModels1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JogoToModels1));
        
        string IMigrationMetadata.Id
        {
            get { return "201405192336518_JogoToModels1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
