// <auto-generated />
namespace Animais360.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UserRedefined : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserRedefined));
        
        string IMigrationMetadata.Id
        {
            get { return "201405140907387_UserRedefined"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
